language: clojure
dist: bionic

env:
  global:
    - JABBA_HOME=/home/travis/.jabba

matrix:
  include:
  - env:
      - ARCHIVE=AnypointStudio66.tar.gz ANYPOINT_STUDIO_URL=https://mule-studio.s3.amazonaws.com/6.6.1-U1/AnypointStudio-for-linux-64bit-6.6.1-201906072050.tar.gz
  - env:
      - ARCHIVE=AnypointStudio73.tar.gz ANYPOINT_STUDIO_URL=https://mule-studio.s3.amazonaws.com/7.3.5-U5/AnypointStudio-for-linux-64bit-7.3.5-201909031749.tar.gz

before_install:
  - lein deps
  - curl -sL https://raw.githubusercontent.com/shyiko/jabba/0.11.2/install.sh | bash && . ~/.jabba/jabba.sh
  - $JABBA_HOME/bin/jabba install
  - jabba install graalvm@19.2.0
  - gu install native-image
install:
  - curl --show-error --fail -o "${ARCHIVE}" "${ANYPOINT_STUDIO_URL}"
  - tar -xzf "${ARCHIVE}"
  - lein compile
before_script:
  - lein run -- -d "AnypointStudio" -o test/mappings generate-mappings
  - lein run -- -d "AnypointStudio" -o test/images extract-images
  - lein run -- -d "AnypointStudio" -o test/images apply-light-theme
script:
  - lein uberjar
  - lein native-image


